version: '3.8'

services:

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
     MYSQL_USER: jpvendas
     MYSQL_PASSWORD: jpvendas
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: jpvendas_db